src/main/java/net/wasdev/wlp/common/plugins/util/InstallFeatureUtil.java

- Remove `getServerFeatures(File serverDirectory, boolean noPluginListedFeatures)` since the server features should be retrieved regardless of plugin listed features.
- Avoid null `to` parameter when setting map value -- if plugin does not provide a default, let the map handle it.

Remove unused method, check for null "to" parameter

---

src/main/java/net/wasdev/wlp/common/plugins/util/InstallFeatureUtil.java

Allow productInfo to be called with different action parameters.  For validate, check the output for "[ERROR]" since the error code is 0 when validation completes with errors.

Allow productInfo to be called with different action parameters

---

pom.xml
src/main/java/net/wasdev/wlp/common/plugins/util/InstallFeatureUtil.java
src/test/java/net/wasdev/wlp/common/plugins/util/InstallFeatureUtilTest.java

This is to address https://github.com/WASdev/ci.maven/issues/343
This does the following:
* Add a dependency on jaxb-api
* Set the parent classloader for the install map
* https://github.com/OpenLiberty/open-liberty/pull/4242 then sets the parent classloader when loading other jars from the install map
* Override the install map with the updated one from the Maven repository.  This will take effect after the updated install map from https://github.com/OpenLiberty/open-liberty/pull/4242 is published.

Add JAXB API into class path when installing features

---

src/main/java/net/wasdev/wlp/common/plugins/util/InstallFeatureUtil.java
src/test/java/net/wasdev/wlp/common/plugins/util/InstallFeatureUtilTest.java

If openliberty.properties is not found, as is the case in WebSphere Liberty 17.0.0.4, a NullPointerException occurs when trying to load the install map override.  The install map override should be skipped in this case.
```
Caused by: java.lang.NullPointerException
at net.wasdev.wlp.common.plugins.util.InstallFeatureUtil.getNextProductVersion(InstallFeatureUtil.java:720)
at net.wasdev.wlp.common.plugins.util.InstallFeatureUtil.downloadOverrideJar(InstallFeatureUtil.java:703)
at net.wasdev.wlp.common.plugins.util.InstallFeatureUtil.loadInstallJarFile(InstallFeatureUtil.java:105)
at net.wasdev.wlp.common.plugins.util.InstallFeatureUtil.<init>(InstallFeatureUtil.java:91)
at net.wasdev.wlp.maven.plugins.server.InstallFeatureMojo$InstallFeatureMojoUtil.<init>(InstallFeatureMojo.java:53)
at …
```

Skip install map override if openliberty.properties not found

---

pom.xml

Fixes #11 
The maven-plugin-plugin seems to have issues with 2.3.0 of jaxb-api, but does not encounter this error with 2.2.12.  Also, although not directly related to this issue, the jaxb-api is not needed during compilation but only during runtime (since it is only the Liberty runtime that requires it when running with Java 9).

Change jaxb dependency

---

src/main/java/net/wasdev/wlp/common/plugins/util/InstallFeatureUtil.java

The install kernel should include a message if the resolved features are empty (in the situation where no features need to be installed).  However, if it does not, we should still consider this as no features need to be installed, and handle it accordingly without NPE.
This addresses https://github.com/WASdev/ci.maven/issues/355

Fix NPE when resolved features are empty but no message exists

---

src/main/java/net/wasdev/wlp/common/plugins/util/InstallFeatureUtil.java
src/test/java/net/wasdev/wlp/common/plugins/util/InstallFeatureUtilGetServerFeaturesTest.java
src/test/resources/servers/server_user_features.xml

According to [Liberty documentation](https://www.ibm.com/support/knowledgecenter/en/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/cwlp_prod_ext.html), features can be defined in the server.xml with the "usr:" prefix or "_extensionName_:" prefix.  Currently `InstallFeatureUtil` treats the entire string as the feature name.  Instead, it should only use the second part as the feature name.

Parse server.xml features without usr prefix

---

src/main/java/net/wasdev/wlp/common/plugins/util/InstallFeatureUtil.java
src/test/java/net/wasdev/wlp/common/plugins/util/InstallFeatureUtilTest.java

Automatic license acceptance should only be for Open Liberty features.  It should not be automatic for WebSphere Liberty features, since some WebSphere Liberty features may have different license terms.  In those cases, the runtime's install kernel should make the determination of whether license acceptance is needed.

Only automatically accept license for Open Liberty features

---

src/main/java/net/wasdev/wlp/common/plugins/util/DevUtil.java
src/test/java/net/wasdev/wlp/common/plugins/util/BaseDevUtilTest.java

- when registering a newly added source directory or test source directory, register it once there is a file in the folders so that the corresponding classes and test-classes folders are created (https://github.com/kathrynkodama/ci.common/blob/723f746bebd1a439ba8a5c8731ca14545976c6f3/src/main/java/net/wasdev/wlp/common/plugins/util/DevUtil.java#L417)
- getArtifacts method returns a `List<String>`
- "Restart dev mode" message if resource directories are added while dev mode is running

fixed resourceDir and srcDir bugs and getArtifacts method

---

src/main/java/net/wasdev/wlp/common/CommonLoggerI.java
src/main/java/net/wasdev/wlp/common/plugins/config/ServerConfigDocument.java

Moving ServerConfigDocument from ci.maven/ci.gradle and fixing issue https://github.com/WASdev/ci.maven/issues/461 (handle defaultValue for variables). Also, fixed code to handle variable values that reference other variables. Pay special attention to methods parseVariables and resolveVariables which is where the majority of the changes were.
Added CommonLoggerI interface which will be implemented in ci.maven and ci.gradle.

Move ServerConfigDocument to common and add common logger interface

---

src/main/java/net/wasdev/wlp/common/plugins/util/DevUtil.java

If a file in config directory is modified and is not server.xml, don't rename it to server.xml.

server.xml in temp dir fix

---

src/main/java/net/wasdev/wlp/common/plugins/util/DevUtil.java

Handles `liberty:stop-server` while dev mode is running and `kill $pid` of the dev mode process.

stop dev mode on server stop

---

src/main/java/net/wasdev/wlp/common/plugins/util/DevUtil.java

Track with a flag whether dev mode stopped the server. If `devStop` is `true` dev mode stopped the server, if `devStop` is `false` an external process stopped the server.

do not throw stop server exception if dev mode stops the server itself

---

src/main/java/io/openliberty/tools/common/plugins/util/ServerFeatureUtil.java
src/test/java/io/openliberty/tools/common/plugins/util/InstallFeatureUtilGetServerFeaturesTest.java

Currently the `install-feature` goal does not support installing user features from the server.xml that are named with `<prefix>:`.  Instead, it should skip them.
Fix for https://github.com/OpenLiberty/ci.maven/issues/537

Skip usr features in server.xml

---

src/main/java/io/openliberty/tools/common/plugins/util/ServerFeatureUtil.java
src/test/java/io/openliberty/tools/common/plugins/util/InstallFeatureUtilGetServerFeaturesTest.java
src/test/resources/servers/bootstrap.properties

This change will allow you to use variables from `bootstrap.properties` inside an include location.
closes #53

Support using variables in include location

---

src/main/java/io/openliberty/tools/common/plugins/util/ServerFeatureUtil.java

- Handle empty server.xml
- Use error handler to prevent fatal errors from printing to console
Part of https://github.com/OpenLiberty/ci.maven/issues/589

Handle empty server.xml

---

pom.xml
src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
src/test/java/io/openliberty/tools/common/plugins/util/DevUtilTest.java

Get debug environment variables for passing to the server startup ant task, in addition to creating server.env.  The task's environment variables will be the default, and the ones in server.env will override them (but they should always be the same).  The port should be consistent between them.
This is needed as part of https://github.com/OpenLiberty/ci.maven/issues/580 so that dev mode (with debug mode) will work on Windows on previous Liberty releases even if the server.bat was not handling server.env properly.

Get debug environment variables for server startup task

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

- Check for server start message
- Throw exceptions if they occur server start instead of logging as debug
- Do not exit dev mode if there is a port conflict
Fixes https://github.com/OpenLiberty/ci.maven/issues/652
Fixes https://github.com/OpenLiberty/ci.maven/issues/653

Check for server start message, log error for port conflict

---

src/main/java/io/openliberty/tools/common/arquillian/objects/LibertyManagedObject.java

Allow setting the property "apiTypeVisibility" in liberty-maven-plugin configuration. See also https://github.com/OpenLiberty/ci.maven/issues/523

Add apiTypeVisibility to LibertyManagedProperty

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
src/test/java/io/openliberty/tools/common/plugins/util/BaseDevUtilTest.java

partial fix for [issue 569](https://github.com/OpenLiberty/ci.maven/issues/569)
Redeploy application if the classes directory must be created (first java class file is created).

redeploy app when classes dir is created

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
src/test/java/io/openliberty/tools/common/plugins/util/BaseDevUtilTest.java

Enables dev mode in Gradle to use the Gradle compiler for recompiling.  Gradle tests depend on compile, so by using Gradle to compile during changes and then run tests (which invokes compile again), it will not recompile the second time.  Also, Gradle does not appear to have the conflict with the Java LS described in https://github.com/OpenLiberty/ci.maven/issues/686.

Enable using build recompiler

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
src/main/java/io/openliberty/tools/common/plugins/util/PluginScenarioException.java

When user types "exit", instead of calling `System.exit(0)`, it should call the shutdown hook to stop dev mode and then just return gracefully from the task.  This is needed for Gradle since Gradle has a long running daemon that is not supposed to exit.
Part of https://github.com/OpenLiberty/ci.gradle/issues/378

Exit dev mode without force stopping JVM

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Decided to warn user to restart dev mode when a resource directory is deleted.  Tracking the files within each resource directory to know which to delete upon deletion of the directory is too expensive.
Fixes https://github.com/OpenLiberty/ci.maven/issues/700

warn user to restart if resource dir is deleted

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
src/test/java/io/openliberty/tools/common/plugins/util/BaseDevUtilTest.java

Partial fix for https://github.com/OpenLiberty/ci.gradle/issues/382
Add a flag to identify if `DevUtil` was called by a Gradle process or not.  If triggered by a Gradle process, skip unit tests and rename integration tests simply to "tests".

Added flag for gradle and changed wording from IT to tests

---

src/main/java/io/openliberty/tools/common/plugins/util/InstallFeatureUtil.java

Fixes https://github.com/OpenLiberty/ci.gradle/issues/397 , but the issue will still be apparent until a newer Liberty version is released that includes the fix for https://github.com/OpenLiberty/open-liberty/issues/10178 (with PR https://github.com/OpenLiberty/open-liberty/pull/10200)
This needs to call the `clear()` method implemented in https://github.com/OpenLiberty/open-liberty/pull/10200 so that the InstallMap can release the jars that it has loaded.
Unfortunately whitespace was also changed by my IDE in the same commit.  The main changes are in the `installFeatures` and `createMapBasedInstallKernelInstance` classes.

Close URLClassLoader and install map resources

---

src/main/java/io/openliberty/tools/common/plugins/util/InstallFeatureUtil.java

… afterwards. This fix is for issue [gradle-402](https://github.com/OpenLiberty/ci.gradle/issues/402)

Disable file caching while we load features in Liberty then restore the caching state

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Fixes https://github.com/OpenLiberty/ci.maven/issues/779
With this fix, adding an empty bootstrap.properties or jvm.options (through either command line or VS Code) causes the server to restart and pick up the changes, and also picks up further changes.

Fix null pointer on empty bootstrap.properties or jvm.options

---

src/main/java/io/openliberty/tools/common/plugins/config/LooseConfigData.java
src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

If you're testing and you have trouble starting a container because port 9443 is in use there is a hidden debug option -D9443 not to generate the option to publish that port. 
Sample test command: mvn -X liberty:dev -Dcontainer -DdockerRun="-v /tmp:/tmp2" -D9443
This sample demonstrates the dockerRun option.

First draft of container support.

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

For dev mode, if compiler options are not specified in the build file, use "-g" to generate all debugging information and "-parameters" to allow reflection access to parameter names.  (We should also handle additional options from the build file, but that should be addressed in a separate PR.)
This partially addresses https://github.com/OpenLiberty/ci.maven/issues/746

Add default compiler options for debugging

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

- libertyInstallFeature() is abstract, so check for container option and skip installing features (for now) in Maven/Gradle instead of here.
- getMessagesLogFile() should avoid using serverTask to get the log file in container mode, the ServerTask did not have its initTask() called yet.

Handle container checks

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

This is the fix for https://github.com/OpenLiberty/ci.gradle/issues/463

Wrap System.in before creating a Scanner so we can close the Scanner cleanly

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Sometimes when you are a non-root user you have permission to modify a file but sometimes the file was created by the docker container. Thus you can get errors trying to modify a file the second time you run dev mode. Thus some error reporting is removed and only available in debug mode. The alternative would be to loop through all the files and not touch files that could not be changed just for the purpose of not generating an error message. 
Fixes https://github.com/OpenLiberty/ci.maven/issues/888

Set up file permissions on Linux to start a container as a non-root user

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

restart the container when using containers.
This code assumes all the files in the config directory in the container are also in the Dockerfile. 
restartServer() defaults to *no* docker build while startServer() defaults to doing a docker build.

Detect when a config file is edited with vim on Linux and

---

pom.xml

ci.ant 1.9.5-SNAPSHOT includes ant security fix

Bump ci.ant dependency to 1.9.5-SNAPSHOT

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

On Linux if the file is missing Docker assumes you want to mount a directory on a directory so it creates the missing directory on the host and the container as required. In the case of our Dockerfile copies like server.xml or bootstrap.properties we need to check if they exist before mounting. Once we support to copy a directory of files in Dockerfile we may need to update this code. 
Fixes https://github.com/OpenLiberty/ci.gradle/issues/519

Only mount the file to the container if it exists.

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

On Linux, run the server on the user id of the current user (the developer). This should be valid because Liberty was designed to be installed by root and then run as a non-root user. 
Also refactored the code that adds the dockerfile copied files to the docker run command.
Fixes https://github.com/OpenLiberty/ci.maven/issues/919

Add --user option to docker run when running on Linux.

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Part of https://github.com/OpenLiberty/ci.maven/issues/927
Add a hotkey where you type 'r' and press Enter to restart the server.  If using container mode, this will rebuild the image and restart the container instead.
Update dev mode startup messages to include this.
Update Dockerfile warnings to suggest this hotkey for the COPY commands that are currently not supported for hot deployment.
Adds formatting to dev mode startup messages as follows:
```
[INFO] *    Liberty dev mode has started!
[INFO] *        To rebuild the Docker image and restart the container, type 'r' and press Enter.
[INFO] *        To stop the server and quit dev mode, press Ctrl-C or …
```

Add hotkey to restart server, add formatting to dev mode startup messages

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

I moved some code around so the diffs look a little bigger.
Also, docker build goes into "console mode" when you redirect the output rather than display it on a terminal.
Fixes OpenLiberty/ci.maven#925

Display stdout and stderr when running docker build just like docker run

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Also improved the stopContainer() not to try to remove the container when it is not found.

When startContainer() fails, check for and remove the left over container.

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Fixes https://github.com/OpenLiberty/ci.maven/issues/946
I am not sure if we should use "Liberty" port or "Application" port.
I also decided to add the debug port as well.
Here are some example outputs with both the errors and startup messages together:
```
[INFO] *    Liberty dev mode has started!
[INFO] *        To rebuild the Docker image and restart the container, type 'r' and press Enter.
[INFO] *        Liberty local http port: 32773
[INFO] *        Liberty local https port: 32772
[INFO] *        Liberty debug port: 7777
[INFO] …
```

946 port properties

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
src/test/java/io/openliberty/tools/common/plugins/util/DevUtilTest.java

On Mac, the string returned from `docker ps` has quotes around each of container names.  Check if the container name has surrounding quotes, and if it does, remove them before processing.
Fixes https://github.com/OpenLiberty/ci.maven/issues/951

Remove quotes before checking container name

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Part of https://github.com/OpenLiberty/ci.maven/issues/952
It will now print something like:
```
[INFO] The server has been restarted.
[INFO] *    Liberty is running in dev mode.
[INFO] *        To rebuild the Docker image and restart the container, type 'r' and press Enter.
[INFO] *        Liberty server HTTP port mapped to Docker host port: 32817
[INFO] *        Liberty server HTTPS port mapped to Docker host port: 32816
[INFO] *        Liberty debug port mapped to Docker host port: 7777
[INFO] ********************************************************************* …
```

Print dev mode startup messages on server/container restart

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Fixes https://github.com/OpenLiberty/ci.maven/issues/962
Also fixes ConcurrentModificationException when registering multiple dockerfileDirectoriesToWatch in the watchFiles loop.
Do we need to build a list of directories registered in case there is an exception? Then remove the list instead of dockerfileDirectoriesToWatch.clear()? It looks like if there *is* an exception then dev mode exits.

Handle Dockerfile ADD commands

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Fixes https://github.com/OpenLiberty/ci.maven/issues/986
Example output:
**dev**
```
[INFO] *    Liberty is running in dev mode.
[INFO] *        To restart the server, type 'r' and press Enter.
[INFO] *    Liberty server port information:
[INFO] *        Liberty server HTTP port: 9080
[INFO] *        Liberty server HTTPS port: 9443
[INFO] *        Liberty debug port: 7777
```
**devc**
```
[INFO] * …
```

986 internal ports

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
src/main/java/io/openliberty/tools/common/plugins/util/JavaCompilerOptions.java
src/test/java/io/openliberty/tools/common/plugins/util/BaseDevUtilTest.java
src/test/java/io/openliberty/tools/common/plugins/util/JavaCompilerOptionsTest.java

Add ability to pass "-source", "-target", "--release", and "-nowarn" options to the compiler.
Part of https://github.com/OpenLiberty/ci.maven/issues/968

Support compiler options for dev mode recompile

---

pom.xml

Updating to ci.ant snapshot for PR OpenLiberty/ci.ant#130.

Update to use ci.ant snapshot

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Fixes https://github.com/OpenLiberty/ci.maven/issues/1000
Example output:
**dev**
```
[INFO] *    Liberty is running in dev mode.
[INFO] *        To restart the server, type 'r' and press Enter.
[INFO] *
[INFO] *    Liberty server port information:
[INFO] *        Liberty server HTTP port: [ 9080 ]
[INFO] *        Liberty server HTTPS port: [ 9443 ]
[INFO] *        Liberty debug port: [ 7777 ]
```
``` …
```

Reformat startup message

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
src/test/java/io/openliberty/tools/common/plugins/util/DevUtilTest.java

Fixes https://github.com/OpenLiberty/ci.maven/issues/947
I duplicated the message and added ‘<‘ to the second copy because of the semantics indicated by the method formatAttentionMessage() which suggests padding could be added to the beginning or the end. Hopefully in the future these messages will be translated and the separate messages should be easier to translate.

Detect when the server http/s ports are used and try the next port in sequence

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
src/test/java/io/openliberty/tools/common/plugins/util/BaseDevUtilTest.java

Used in two places: control tempDockerfile.deleteOnExit() and in cleanUpTempDockerfile() called from shutdown hook.

Add keepTempDockerfile option

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
src/test/java/io/openliberty/tools/common/plugins/util/DevUtilTest.java

Fixes https://github.com/OpenLiberty/ci.maven/issues/987
Here is some example output below. Specifically, I'm interested to know if the warning and/or the debug statements should be allowed to break up the startup message box. 
**Example Output**
One network:
```
[INFO] *    Liberty is running in dev mode.
[INFO] *        To rebuild the Docker image and restart the container, type 'r' and press Enter.
[INFO] *
[INFO] *    Liberty container port information:
[INFO] *        Internal container HTTP port [ 9080 ] is mapped to Docker host port [ 32835 ]
[INFO] * …
```

987 network info

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
src/test/java/io/openliberty/tools/common/plugins/util/DevUtilTest.java

Seems the loopback address parts are not applicable to ports being used by Docker on Windows.  Changed it to be more generic.
Fixes https://github.com/OpenLiberty/ci.maven/issues/1033

Fix finding of available port on Windows

---

src/main/java/io/openliberty/tools/common/plugins/util/ServerFeatureUtil.java

Partial fix for https://github.com/OpenLiberty/ci.maven/issues/1039
This fix handles references to predefined Liberty server directory properties in the server.xml include location. It also eliminates the "Illegal group reference" error for all cases. For variables that are not resolved, a warning is logged.
The following are still not handled:
- resolving variables defined in server.xml (or files it includes)
- resolving references to env properties
- resolving references to server.env properties

Fix problem with resolving Liberty predefined server dir properties

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
src/main/java/io/openliberty/tools/common/plugins/util/OSUtil.java

Fixes https://github.com/OpenLiberty/ci.maven/issues/1045
Also increase docker command timeouts from 10s to 20s except server stop from 30s to 40s. VMs can be slower than physical machines.

Set DOCKER_BUILDKIT=0 environment var for docker build and run on Mac and Windows

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
src/test/java/io/openliberty/tools/common/plugins/util/DevUtilPrepareDockerfileTest.java

Fixes https://github.com/OpenLiberty/ci.maven/issues/1061
- Only display RUN features.sh warning message if all of these conditions are met: server still is starting up, Dockerfile does not have `RUN features.sh`, and the message has not been displayed before during this startup session.

Fix when to display features warning message

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Basically two warnings (possibly) in one message because they are related. 
Fixes: https://github.com/OpenLiberty/ci.maven/issues/1069

Update slow docker build message to account for RUN features.sh command.

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

When recompiling in dev mode for Maven, do not include the current classloader (of Liberty Maven plugin) for determining the compile classpath.  Instead, it should only use the artifacts defined in the Maven project for the classpath.
Fixes https://github.com/OpenLiberty/ci.maven/issues/1081

Do not add current classloader to compile classpath

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

This restart is caused by some of the Liberty config files being changed.

Add call to regenerate the feature list when recreating and restarting the server

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

For Maven multi module projects, dev mode adds jars to the classpath and the current project's target classes dir, but should also include other modules' target classes directories as well.

Add directories to compile classpath

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
src/test/java/io/openliberty/tools/common/plugins/util/DevUtilTest.java

In a multi module project, if the projectDirectory and the multiModuleProjectDirectory are different, use the longest common directory as the project root for mounting the loose application files to container.

Use common parent directory when mounting loose application in container

---

pom.xml
src/main/java/io/openliberty/tools/common/arquillian/objects/LibertyManagedObject.java

Part of https://github.com/OpenLiberty/ci.maven/issues/1131
If the userDirectory parameter is passed in, write its value to the `arquillian.xml` file for the `usrDir` property, but only if it is not overridden by an `arquillianProperties` configuration property.

Bump ci.ant version and handle userDirectory configuration for arquillian

---

pom.xml
src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
src/main/java/io/openliberty/tools/common/plugins/util/UpstreamProject.java
src/test/java/io/openliberty/tools/common/plugins/util/BaseDevUtilTest.java

Adds support for hot compilation of multi module projects. Tracks upstream projects and supports the following scenarios:
- Source compilation of upstream projects
- change in source code triggers hot compilation of that class. If successful, tries compiling any projects with compilation failures
- on first watch loop, skips attempting to recompile projects with compilation failures (to avoid multiple compilations if a user starts dev mode with some compile errors)
- in the multi-module scenario messages will specify the module they relate to, ie. `guide-maven-multimodules-jar source compilation was successful.`
- Watching `pom.xml` of upstream projects
- updates the classpath used for compilation for the corresponding project
- tries recompiling any projects with compilation failures (in …

Multi-module support for hot source compilation

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
src/main/java/io/openliberty/tools/common/plugins/util/UpstreamProject.java
src/test/java/io/openliberty/tools/common/plugins/util/BaseDevUtilTest.java
src/test/java/io/openliberty/tools/common/plugins/util/DevUtilRunTestThreadTest.java

Adds support for hot compilation of test directories for multi module Maven projects, and supports running tests across all modules.
- Dev mode watches the test directories of the different modules, and on save will recompile. On a successful recompile, dev mode will try to recompile any other failing classes within the same module. 
- On Enter, all tests across all modules will be run. The `upstreamProjects` object is now a List instead of a Set, to ensure that when tests are run for all modules, they will match the reactor build order. 
- If the `hotTests` flag is enabled, only the tests corresponding to the module changed will be run (the `runTests` method now accepts build file(s), and will run tests against the build file(s) specified). If the `hotTests` flag is enabled, handle the …

Support hot compilation of and running tests for multi module Maven projects

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
src/main/java/io/openliberty/tools/common/plugins/util/UpstreamProject.java

Fixes https://github.com/OpenLiberty/ci.maven/issues/1164
Supports adding a new test directory for an upstream module once dev mode has started. This applies only to the multi-module Maven scenario.

Support adding a new test dir for an upstream module

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

When devc issues the `docker run` command, append [WLP_DEBUG_REMOTE environment var](https://github.com/OpenLiberty/open-liberty/blob/2fd4a880754c37a988c5ed9ac4f1ea5988e465d6/dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server#L58) as WLP_DEBUG_REMOTE=y to allow remote debugging on newer Java versions such as 11.
Fixes https://github.com/OpenLiberty/ci.maven/issues/1161

Add env var to allow remote debug

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Fixes https://github.com/OpenLiberty/ci.maven/issues/1160
Rather than searching for the updated message code + application id in the logs, only search for the code. This will validate that the application has updated in a single module scenario, as it will search for 1  new updated message in log.  This will also validate that the application(s) update in a multi module scenario, as it will check that there is 1+ new updated messages in the log. See the corresponding [waitForUpdatedStringInLog](https://github.com/OpenLiberty/ci.ant/blob/92e3595d552f3e3ebb9c0f726f74d469fc5c2264/src/main/java/io/openliberty/tools/ant/AbstractTask.java#L516-L555) method in ci.ant.
ci.maven and ci.gradle dev mode tests passed locally. 

Dev mode should search for only the start/update code in logs

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
src/main/java/io/openliberty/tools/common/plugins/util/UpstreamProject.java

Fix for https://github.com/OpenLiberty/ci.maven/issues/1159
See corresponding ci.maven PR: https://github.com/OpenLiberty/ci.maven/pull/1167
- Dev mode will honour the Maven compiler options set for multi module projects
- Dev mode will watch the pom.xml (single module and multi module projects) for changes to the Maven compiler options. Any changes will take effect on future compilation calls. Marked as a "TODO" is to recompile the entire module when there is a change to the Maven compiler options.

Dev mode support for multi module compiler options

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
src/main/java/io/openliberty/tools/common/plugins/util/ProjectModule.java
src/test/java/io/openliberty/tools/common/plugins/util/BaseDevUtilTest.java

**Java compilation**
Part of https://github.com/OpenLiberty/ci.maven/issues/1174
Default behaviour for `recompileDependencies` is set in ci.maven/ci.gradle.
When `recompileDependencies=true` recompile all classes in the current and dependent modules when a:
- src/main/java file is added, modified or deleted
- src/test/java files is added, modified or deleted
- build file changes
For multi module projects, when `recompileDependencies=true` always compile in build order: 
1) Failing classes from any upstream modules
2) All classes in the current module
3) All classes in any dependent (downstream) modules
DevUtil uses a `disableDependencyCompile` flag for each project to only compile the current module. This is needed to avoid duplication compilation is step (3) above. 
**multi module …

Add recompileDependencies option for dev mode and default behaviour

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Partial fix for https://github.com/OpenLiberty/ci.maven/issues/1175 (integration tests in ci.maven still need to be added) 
When `hotTests=true` for multi-module projects, always run tests on the modified module and all dependent modules.
Since we have to run tests using the same `ThreadPoolExecutor`, for multi-module projects do not run tests through `recompileJavaSource` or `recompileJavaTest` (that is why [skipRunningTests is true](https://github.com/OpenLiberty/ci.common/pull/275/files#diff-d8b4217f048364ad127bea282a1726d1523aa8359775cee2f4b71eec9cba7140R2979-R2985) when called from `processUpstreamJavaCompilation`). Instead, call `runTestThread()` directly and pass in the current build file and all dependent build files. 

Add hotTests logic for multi module projects

---

src/main/java/io/openliberty/tools/common/plugins/util/InstallFeatureUtil.java

Related to https://github.com/OpenLiberty/open-liberty/issues/17843
Due to this [PR](https://github.com/OpenLiberty/open-liberty/pull/17319/files#) in installKernelMap, starting 21.0.0.7 plugins started to use `resolve` API instead of `resolveAsSet`. The main difference between the `resolve` and `resolveAsSet` is that resolveAsSet assumes all the resources should start together on one server and detects conflicts.
Changing the plugins behaviour back to using `resolveAsSet` as it only targets 1 server at a time.

use resolveAsSet

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
src/test/java/io/openliberty/tools/common/plugins/util/BaseDevUtilTest.java

- Call test compile for the corresponding module when a `src/test/java` directory is added to an upstream project (and test compile on all dependent modules) 
- Run tests after a `src/main/java` directory is added for single module projects, or the module with the Liberty configuration for multi-module projects

Compile dependent modules when test dir is added to an upstream module

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
src/main/java/io/openliberty/tools/common/plugins/util/ProjectModule.java

Per https://github.com/OpenLiberty/ci.maven/issues/1202 deliver a warning to users if a `src/main/java` directory of an upstream project is added or deleted. Users should restart dev mode as the classpaths will not be correct between dependent modules.

Warn users to restart dev mode if an upstream source directory is added

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

For multi-module projects with `-DhotTests=true`, only run tests when all compilations are successful. 
For multi module projects with `-DrecompileDependencies=true` (default) and `-DhotTests=true`, compilation occurs in the following order:
1. Compile any failing source and test classes in upstream modules 
2. Compile all source and test classes in the module where the file was changed
3. Compile all source and test classes in the dependent modules
4. if ALL of the above compilations were successful, run tests on the current module (step 2) and all dependent modules (step 3)
*if a test file was changed, steps 1-4 are the same except only test classes will be compiled
For multi module projects with `-DrecompileDependencies=false` and `-DhotTests=true`, compilation occurs in the following …

Multi-module projects run tests when all compilations are successful

---

.github/workflows/maven.yml

The maven version recently changed from 3.8.1 to 3.8.2, which introduced this bug in our builds (for ci.ant and ci.maven):
https://www.mail-archive.com/issues@maven.apache.org/msg189865.html
Adding specific 3.8.1 maven version to our build yaml file to be consistent across our builds.

Specify maven version in build yaml

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
src/test/java/io/openliberty/tools/common/plugins/util/BaseDevUtilTest.java

Adding the `generateFeatures` parameter in order to move forward with other prototype/development items.

Dev mode, generate features: add generateFeatures parameter 

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
src/main/java/io/openliberty/tools/common/plugins/util/InstallFeatureUtil.java

For `devc`, run server commands without the absolute path, since the Liberty bin directory is in $PATH for both Open Liberty and WebSphere Liberty container images.
Fixes https://github.com/OpenLiberty/ci.maven/issues/1246

Run container server commands from PATH

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
src/test/java/io/openliberty/tools/common/plugins/util/BaseDevUtilTest.java
src/test/java/io/openliberty/tools/common/plugins/util/BaseInstallFeatureUtilTest.java
src/test/java/io/openliberty/tools/common/plugins/util/DevUtilHostnamePortTest.java
src/test/java/io/openliberty/tools/common/plugins/util/DevUtilRunTestThreadTest.java
src/test/java/io/openliberty/tools/common/plugins/util/DevUtilTest.java
src/test/java/io/openliberty/tools/common/plugins/util/InstallFeatureUtilGetInstallMapTest.java
src/test/java/io/openliberty/tools/common/plugins/util/InstallFeatureUtilGetServerFeaturesTest.java
src/test/java/io/openliberty/tools/common/plugins/util/InstallFeatureUtilTest.java

- Use `target/.libertyDevc` or `build/.libertyDevc` for temp Dockerfile location instead of $TEMP, so that paths can be relativized
- Cleanup imports in tests
Fixes https://github.com/OpenLiberty/ci.maven/issues/1044

Use build dir for temp Dockerfile, cleanup imports

---

src/main/java/io/openliberty/tools/common/plugins/config/ServerConfigDropinXmlDocument.java
src/main/java/io/openliberty/tools/common/plugins/config/ServerConfigXmlDocument.java
src/main/java/io/openliberty/tools/common/plugins/config/XmlDocument.java
src/test/java/io/openliberty/tools/common/plugins/util/ServerConfigFileTest.java

This code is in ServerConfigDropinXmlDocument which is not a great name for the purpose to which it is now being put. This class is now used also to handle server.xml files where previously it just created the variable xml files and the generated features xml files.
We could create a new class with a name such as ServerConfigXmlDocument which extends ServerConfigDropinXmlDocument if we want to separate the server.xml handling. I'm not thrilled with that hierarchy so we could create a new common sub-class both these classes could extend.
Let me know what you think.
Also, do you know why XmlDocument wants to ignore comments?

Read config document from file and process as server.xml with featureManager element

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Fixes https://github.com/OpenLiberty/ci.maven/issues/1269
Fixes https://github.com/OpenLiberty/ci.maven/issues/1266
Screenshot showing the following sequence:
1. Dev mode startup with flag status (feature gen on)
2. h (feature gen is on) - notice g and o are in the help menu
3. o to optimize
4. g (turn feature gen off)
5. h (feature gen is off) - notice o is not in the help menu
6. o - gets warning that feature gen is off
7. g (turn feature gen on) - also triggers optimize

Add g and o hotkeys, show feature gen flag status

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
src/main/java/io/openliberty/tools/common/plugins/util/ServerFeatureUtil.java
src/test/java/io/openliberty/tools/common/plugins/util/InstallFeatureUtilGetServerFeaturesTest.java
src/test/resources/servers/generated-features.xml

Part of https://github.com/OpenLiberty/ci.maven/issues/1294
- Call generateFeatures when optimizing features in dev mode
- Omit previously generated features when optimizing features
- Add unit test for getting list of features without specific dropins files
Note: This gets the correct optimized result from binary scanner but does not yet properly write the optimized features to the generated file.

Omit previously generated features when optimizing features

---

src/main/java/io/openliberty/tools/common/plugins/config/LooseConfigData.java
src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
src/test/java/io/openliberty/tools/common/plugins/util/BaseDevUtilTest.java
src/test/java/io/openliberty/tools/common/plugins/util/DevUtilTest.java
src/test/resources/servers/looseApp.xml

Adds logic to not watch files that are in the source directory and specified in the loose application file.
Part of https://github.com/OpenLiberty/ci.maven/issues/1285

Do not watch files that are in the source directory and the loose app config file

---

src/main/java/io/openliberty/tools/common/plugins/config/ServerConfigXmlDocument.java
src/main/java/io/openliberty/tools/common/plugins/config/XmlDocument.java
src/test/java/io/openliberty/tools/common/plugins/util/ServerConfigFileTest.java

Also return true if adding a comment to XML document is successful. Update test.
The document will have indentation embedded in the case it is read from a file by the parser. The embedded spaces appear as Text nodes which contain, for example, \n<blank><blank><blank><blank>. The code currently checks for these spaces. 
Another design would be to overload the setXmlStandalone() flag which is set when the document is created internally and is currently not set by the parser when the document is read from a file. We could control the indentation using that flag. 
Alternatively do the reviewers know of other W3C Document (org.w3c.dom.Document) properties which could indicate embedded indentation whitespace?
Fixes https://github.com/OpenLiberty/ci.maven/issues/1301

Write XML document without indentation if the document has indentation embedded in it.

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
src/test/java/io/openliberty/tools/common/plugins/util/BaseDevUtilTest.java

Reverts changes introduced in: https://github.com/OpenLiberty/ci.common/pull/301/files
See https://github.com/OpenLiberty/ci.maven/pull/1305 for reference 

Revert valid classpath check as dev mode is blocked for invalid Maven versions

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Fixes item (2) from https://github.com/OpenLiberty/ci.gradle/issues/662#issuecomment-985025788 by removing generateFeatures call during initial compile steps after dev mode startup.  Note that class files are not updated during this initial compile because they were already compiled on dev mode startup (and this initial compile's only purpose is to show compile errors if any), so feature generation does not run from the watch loop at this point.
This fix should be used along https://github.com/OpenLiberty/ci.gradle/pull/661 which handles item (1) by adding a generateFeatures call to dev mode startup steps in Gradle.

Remove extra generate features from gradle initial compile

---

pom.xml
src/main/java/io/openliberty/tools/common/plugins/config/ServerConfigXmlDocument.java
src/main/java/io/openliberty/tools/common/plugins/util/BinaryScannerUtil.java

Only one more recursion check is needed on top of the new plugin exceptions added in #327 
Fixes #326
Fixes https://github.com/OpenLiberty/ci.maven/issues/1341

Remove unused dependencies and protect recursion in runBinaryScanner().

---

src/main/java/io/openliberty/tools/common/plugins/util/BinaryScannerUtil.java

Fixes https://github.com/OpenLiberty/ci.maven/issues/1344
I think the recursive nature of the first effort was too complex. Splitting the method in two is a little repetitive but well worth it for simplicity and maintainability.

Refactor the method which calls the binary scanner into two pieces for clarity and ease of maintenance

---

src/main/java/io/openliberty/tools/common/plugins/util/BinaryScannerUtil.java

Bump lower bound of binary scanner version to `21.0.0.5-SNAPSHOT`
See https://github.com/OpenLiberty/ci.maven/issues/1321#issuecomment-1021468911 

Move binary scanner maven artifact constants to BinaryScannerUtil and bump binary scanner version

---

src/main/java/io/openliberty/tools/common/plugins/util/BinaryScannerUtil.java

Part of https://github.com/OpenLiberty/ci.maven/issues/1321 and https://github.com/OpenLiberty/ci.gradle/issues/665
Applies to the "optimize=true" scenario.
Rather than throwing an error when class directories do not exist, return an empty string. Then the binary scanner will be called with an empty string for `binaryInputs`, so that it will still detect conflicts between user specified features.

Binary scanner, return empty array when class directories do not exist rather than an error

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Fixes https://github.com/OpenLiberty/ci.maven/issues/1366
Added line to https://github.com/OpenLiberty/ci.maven/issues/1395 to handle integration tests for this scenario.

1366 server.xml feature removal

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
src/main/java/io/openliberty/tools/common/plugins/util/ServerFeatureUtil.java
src/test/java/io/openliberty/tools/common/plugins/util/BaseDevUtilTest.java
src/test/java/io/openliberty/tools/common/plugins/util/DevUtilTest.java

Part of https://github.com/OpenLiberty/ci.maven/issues/1431
On any config XML file change (added, modified, deleted, also including the `serverXmlFile` custom server.xml) check if features have been modified. If they have, call optimizeGenerateFeatures()
Renames the following methods to more descriptive names:
- `checkConfigFolder` --> `installFeaturesToTempDir`
- `checkConfigFile` --> `installFeatures`

Generate features when config xml file modified and features have been modified

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
src/test/java/io/openliberty/tools/common/plugins/util/BaseDevUtilTest.java

Pass generateFeatures boolean to `recompileBuildFile` and `updateArtifactPaths` methods
Part of https://github.com/OpenLiberty/ci.maven/issues/1441

Pass generateFeatures boolean to build file updated methods

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
src/main/java/io/openliberty/tools/common/plugins/util/ServerFeatureUtil.java

Improve the "Parsing the server file for features and includes" message to list the paths relative to the server directory.
```
[INFO] CWWKM2102I: Using serverName : defaultServer.
[INFO] CWWKM2102I: Using serverDirectory : /Users/kathrynkodama/devex/featureGeneration/snapshot-testing/demo-devmode/target/liberty/wlp/usr/servers/defaultServer.
[INFO] Parsing the server file for features and includes: defaultServer/configDropins/defaults/install_apps_configuration_1491924271.xml
[INFO] Parsing the server file for features and includes: defaultServer/server.xml
[INFO] Parsing the server file for features and includes: defaultServer/extraFeatures1.xml
[INFO] Parsing the server file for features and includes: defaultServer/extraServerConfig1.xml
[INFO] Parsing the server file for features and …
```

Improve log message when parsing server files for features

---

src/main/java/io/openliberty/tools/common/plugins/util/BinaryScannerUtil.java

Part of https://github.com/OpenLiberty/ci.maven/issues/1497
When a `ProvidedFeatureConflictException`, `FeatureConflictException` or `RequiredFeatureModifiedException` is returned from the binary scanner, we do not need to call it again if we have already generated features for all class files (optimize = true) and we did not pass any user specified features (currentFeatureSet is empty).

Do not rerun binary scanner if optimizing and there are no user specified features

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Fixes https://github.com/OpenLiberty/ci.maven/issues/1512
Copy the generated-features.xml file to the server directory on server.xml or other xml config file changes if the generated features have changed.
Updated logic flow is:
1. server.xml (or another server configuration xml file) updated, FileWatcher indicates a server config file has been modified
2. features are generated
3. copy server.xml and generated-features.xml to temp server dir
4. install features given the temp server dir
5. copy the server.xml to the target dir
6. if the features in generated-features.xml file have changed, copy the generated-features.xml file to target dir 
7. FileWatcher indicates that the generated-features.xml file has been modified, however the features have not changed so do not copy the file to …

If needed copy the generated-features.xml file to the server directory on config file change

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Also, display warning when action is unrecognised.
Fixes  https://github.com/OpenLiberty/ci.maven/issues/1446
`Enter - Tests will run automatically when changes are detected. You can also press the Enter key to run tests on demand.` is difficult to reword. This message appears when `hotTests` is on so you don't usually press Enter to run the tests. I think the most important part of this message is to say tests run automatically. The second most important part is to press Enter to run the tests again on demand. 
```
[INFO] *        Automatic generation of features: [ On ]
[INFO] *        g - toggle the automatic generation of features, type 'g' and press Enter.
[INFO] *        o - optimize the list of …
```

Display the action letter before the description of the action.

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
src/test/java/io/openliberty/tools/common/plugins/util/BaseDevUtilTest.java

Fixes https://github.com/OpenLiberty/ci.maven/issues/1513
Much of the logic for a configuration file change or a configured custom server.xml file (serverXmlFile configuration parameter) is the same. Refactored this logic into a common method.

Update existing feature list even if install feature was unsuccessful

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Toggling generate features on after dev mode as started:
```
h
[INFO] *        Automatic generation of features: [ Off ]
[INFO] *        g - toggle the automatic generation of features, type 'g' and press Enter. A new server configuration file will be generated in the SOURCE configuration directory.
[INFO] *        Enter - run tests on demand, press Enter.
[INFO] *        r - restart the server, type 'r' and press Enter.
[INFO] *        h - see the help menu for available actions, type 'h' and press Enter.
[INFO] *        q - stop the server and quit dev mode, press Ctrl-C or type 'q' and press Enter.
g
[INFO] Setting automatic …
```

Add warning messages for generate features generating to source dir

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Fixes https://github.com/OpenLiberty/ci.maven/issues/1545
Previous file path comparison was not valid for Windows
Confirmed that this fix is valid for MacOS

Fix file comparison for generated features file

---

src/main/java/io/openliberty/tools/common/plugins/util/BinaryScannerUtil.java

Instead of hard coding the parameters passed to the binary scanner we will compose the parameter from the information in the build file. If the build file specifies a version number that the binary scanner does not support it will throw an invalid argument exception which we report.
This pull request is also a bit of a design review. We could request a better API from the binary scanner regarding invalid version numbers but the current arrangement looks pretty safe. Also the message we report should be reviewed.

Compose version parameters for binary scanner and handle errors

---

src/main/java/io/openliberty/tools/common/plugins/util/BinaryScannerUtil.java

This support will be added in the 22.0.0.4 (or later) version of the binary scanner and this code continues to work with the 22.0.0.3 version which is currently available.

Add support for the binary scanner checking the validity of the target versions for ee and mp

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
src/test/java/io/openliberty/tools/common/plugins/util/BaseDevUtilTest.java
src/test/java/io/openliberty/tools/common/plugins/util/DevUtilTest.java

Screenshot demonstrated with the liberty starter-app
File is written out to `{buildDir}/{serverName}-liberty-devc-metadata.xml`
The original file gets replaced if/when written to the same place when stopped.

write liberty-dev-metadata when using devc

---

src/main/java/io/openliberty/tools/common/plugins/util/InstallFeatureUtil.java
src/test/java/io/openliberty/tools/common/plugins/util/BaseInstallFeatureUtilTest.java
src/test/java/io/openliberty/tools/common/plugins/util/InstallFeatureUtilTest.java

Related to https://github.com/OpenLiberty/liberty-language-server/issues/101.
Deleting the `.libertyls` directory (which contains generated schema files from Liberty Tools) when features are installed since the previously generated schema is no longer correct.
Had to pass in the build directory since that is where the `.libertyls` directory would be located. Maven and Gradle PRs are coming to reflect this change.

Enable schema regen for Liberty Tools

---

src/main/java/io/openliberty/tools/common/plugins/util/InstallFeatureUtil.java
src/main/java/io/openliberty/tools/common/plugins/util/ServerFeatureUtil.java
src/test/java/io/openliberty/tools/common/plugins/util/InstallFeatureUtilTest.java

https://github.com/OpenLiberty/ci.maven/issues/1532
Copy user feature jar and manifest file to Liberty image when installFeatureUtility/featureUtility is not available (for Liberty 21.0.0.11 or below).

copy user feature for older liberty versions

---

pom.xml

* extract version into property to be consumed by ci.maven
* Scope is prerequisite for https://github.com/OpenLiberty/ci.maven/issues/1691
* extraction is sensible for using the same version in ci.maven.

[#404] fix scope for maven-artifact

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
src/main/java/io/openliberty/tools/common/plugins/util/OSUtil.java
src/main/java/io/openliberty/tools/common/plugins/util/VersionUtility.java

This fixes errors reported in https://github.com/OpenLiberty/ci.maven/issues/1722 and probably https://github.com/OpenLiberty/ci.maven/issues/1671.

Fix devc permissions issues for Docker

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Fixes Podman build logging showing up as an error level message.
Error messages:
Fixed info messages:

Fix container builds logging info as error on Linux

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Fix for https://github.com/OpenLiberty/ci.maven/issues/1741
1. Increased timeout on file watcher getEvents() method. For some reason, it was taking longer in more recent version of the plugin. This cause the code to fall back to polling.
2. Fix polling problem on file monitoring. Need to handle watching multiple files in a single directory.

Fix for dev mode file watching problem

---

src/main/java/io/openliberty/tools/common/plugins/util/InstallFeatureUtil.java
src/main/java/io/openliberty/tools/common/plugins/util/PrepareFeatureUtil.java
src/main/java/io/openliberty/tools/common/plugins/util/ServerFeatureUtil.java
src/test/java/io/openliberty/tools/common/plugins/util/BaseInstallFeatureUtilTest.java
src/test/java/io/openliberty/tools/common/plugins/util/InstallFeatureUtilGetInstallMapTest.java
src/test/java/io/openliberty/tools/common/plugins/util/InstallFeatureUtilTest.java

In addition to https://github.com/OpenLiberty/open-liberty/issues/17220.
FeatureUtility now verifies downloaded features from Maven Central. Enabling the same functionality for Liberty Maven Plugin's `install-feature` goal and Liberty Gradles Plugin's `installFeature` task.

Enable signature verification for feature install 

---

.github/workflows/maven.yml
src/main/java/io/openliberty/tools/common/plugins/config/ServerConfigDocument.java
src/main/java/io/openliberty/tools/common/plugins/util/ServerFeatureUtil.java
src/test/java/io/openliberty/tools/common/plugins/util/InstallFeatureUtilGetServerFeaturesTest.java
src/test/java/io/openliberty/tools/common/plugins/util/ServerConfigDocumentTest.java
src/test/resources/serverConfig/liberty/wlp/usr/servers/defaultServer/includeDir/anotherInclude.xml
src/test/resources/serverConfig/liberty/wlp/usr/servers/defaultServer/includeDir/yetAnotherInclude.xml
src/test/resources/serverConfig/liberty/wlp/usr/servers/defaultServer/server.xml
src/test/resources/servers/includeDir/extraFeatures.xml
src/test/resources/servers/includeDir/extraFeatures2.xml
src/test/resources/servers/includeDir/extraFeatures4.xml
src/test/resources/servers/server_dir_ignore.xml
src/test/resources/servers/server_dir_replace.xml

Fixes OpenLiberty/ci.maven#1720
When a directory is specified in `<include>`, parse all direct children xml files alphabetically.
Added tests for directory include support.

Support directory as valid location to include in server configuration

---

src/main/java/io/openliberty/tools/common/plugins/config/ServerConfigDocument.java
src/main/java/io/openliberty/tools/common/plugins/util/InstallFeatureUtil.java
src/main/java/io/openliberty/tools/common/plugins/util/ServerFeatureUtil.java
src/main/java/io/openliberty/tools/common/plugins/util/VariableUtility.java
src/test/java/io/openliberty/tools/common/plugins/util/BaseInstallFeatureUtilTest.java
src/test/java/io/openliberty/tools/common/plugins/util/InstallFeatureUtilGetServerFeaturesTest.java
src/test/resources/serverConfig/liberty/wlp/usr/servers/defaultServer/server.xml
src/test/resources/servers/server_dir_ignore.xml
src/test/resources/servers/server_dir_replace.xml

Match Liberty behavior where <include> directory has to end in File.separator
> Note: Both Liberty and our test code convert Windows `\` into `/`, so all the logic uses `/`
Note implemented behavior in https://github.com/OpenLiberty/ci.common/pull/426#discussion_r1373606247

Modify behavior for include directory to match Liberty

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Fixed writers not closing fully in `writeDevcMetadata()` and changed `execContainerCmdAndLog()` to only write devc metadata file on container start/stop commands.
Fixes: https://github.com/OpenLiberty/ci.maven/issues/1746

Update devc metadata file write behavior for container build and start

---

src/main/java/io/openliberty/tools/common/plugins/config/ServerConfigDocument.java
src/main/java/io/openliberty/tools/common/plugins/util/ServerFeatureUtil.java

- Use case-insensitive sort for dir files to match Liberty behavior.
- Fix configDropins processing to sort alphabetically
- Simplified and refactored some code.
Current 23.0.0.10 release has a bug where it uses case-sensitive sort for `<include>` dirs.
Fix in open-liberty went in recently, and will be in the 23.0.0.12 release

Correctly sort dir files alphabetically to match Liberty behavior

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
src/test/java/io/openliberty/tools/common/plugins/util/DevUtilTest.java

Fix related to https://github.com/OpenLiberty/liberty-language-server/issues/253. The Liberty Config Language Server expected `containerType` instead of `containerEngine` for the xml element name indicating whether docker or podman was being used. Since that is the only consumer of this information so far, decided to make the change here since we plan to do a release soon.

Change containerEngine to containerType

---

src/main/java/io/openliberty/tools/common/plugins/util/InstallFeatureUtil.java
src/main/java/io/openliberty/tools/common/plugins/util/ServerFeatureUtil.java

Related to issue https://github.com/OpenLiberty/ci.gradle/issues/867

Remove kernel logging for non-debug case

---

src/main/java/io/openliberty/tools/common/plugins/config/ServerConfigDocument.java
src/main/java/io/openliberty/tools/common/plugins/util/ServerFeatureUtil.java
src/test/java/io/openliberty/tools/common/plugins/util/ServerConfigDocumentTest.java

Related to https://github.com/OpenLiberty/ci.maven/issues/1693

Remove static vars from ServerConfigDocument

---

src/main/java/io/openliberty/tools/common/plugins/util/ServerFeatureUtil.java

Work around for LGP issue: https://github.com/OpenLiberty/ci.gradle/issues/867

Work around for LGP issue 867

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

For internally reported issue with running devc on LMP 3.10.1. The same scenario worked on LMP 3.10. The error reported was:
```
[ERROR] Failed to execute goal io.openliberty.tools:liberty-maven-plugin:3.10.1:devc (default-cli) on project guide-testcontainers: Error starting the server in dev mode.: An error occurred while running the container: docker: Error response from daemon: unable to find user 0 : no matching entries in passwd file. RC=125 -> [Help 1]
```
There seems to be a trailing space for the `--user 0 ` on the `docker run` command. The changes made in [PR](https://github.com/OpenLiberty/ci.common/pull/441) causes this space to be preserved, whereas it would have been trimmed previously.

Trim user id before adding to docker run command

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
src/test/java/io/openliberty/tools/common/plugins/util/DevUtilTest.java

This addresses a deficiency in the handling of containerRunOpts that contains spaces in the option values.

Handle splitting of containerRunOpts correctly

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

For issue https://github.com/OpenLiberty/ci.gradle/issues/889

Update messages related to running tests when skipTests is set to true

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
src/main/java/io/openliberty/tools/common/plugins/util/InstallFeatureUtil.java
src/main/java/io/openliberty/tools/common/plugins/util/ServerFeatureUtil.java
src/test/java/io/openliberty/tools/common/plugins/util/InstallFeatureUtilGetServerFeaturesTest.java
src/test/java/io/openliberty/tools/common/plugins/util/InstallFeatureUtilTest.java
src/test/resources/servers/config_defaults.xml
src/test/resources/servers/config_overrides.xml
src/test/resources/servers/extraFeatures2.xml
src/test/resources/servers/server.xml
src/test/resources/servers/server_multiple_merge.xml

The parsing logic now collects `<platform>` elements along with `<features>`

Start parsing platforms, along with features in featureManager node

---

src/main/java/io/openliberty/tools/common/plugins/util/InstallFeatureUtil.java

Versionless feature support was added in 24.0.0.8, but some important fixes went into 24.0.0.9. Better to steer people to use that version.

Update min version to 24.0.0.9 for versionless features

---

src/main/java/io/openliberty/tools/common/plugins/util/ServerFeatureUtil.java
src/test/java/io/openliberty/tools/common/plugins/util/InstallFeatureUtilGetServerFeaturesTest.java
src/test/resources/servers/noList_nested_features.xml
src/test/resources/servers/server_merge_nested.xml

Before this fix, the additional test case added by this PR received the following exception:
```
[ERROR] Errors: 
[ERROR]   InstallFeatureUtilGetServerFeaturesTest.testNestedMergeServerXML:174->verifyServerFeatures:73 » NullPointer Cannot invoke "io.openliberty.tools.common.plugins.util.ServerFeatureUtil$FeaturesPlatforms.getFeatures()" because "result" is null
```
Related to https://github.com/OpenLiberty/ci.maven/issues/1838

Prevent NPE for nested include files with no featureManager element

---

src/main/java/io/openliberty/tools/common/plugins/config/ServerConfigDocument.java
src/test/java/io/openliberty/tools/common/config/ServerConfigDocumentOverridesTest.java
src/test/resources/serverConfig/liberty/wlp/usr/servers/defaultServer/server.xml
src/test/resources/servers/springBootApplicationTest/included_server.xml

springbootapplication node multiple occurrence fix

---

src/main/java/io/openliberty/tools/common/plugins/util/BinaryScannerUtil.java

This specifies the latest binary scanner on Maven Central.
Responding to https://github.com/OpenLiberty/ci.maven/issues/1874

Specify version 24.0.0.2 for binary scanner

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
src/test/java/io/openliberty/tools/common/plugins/util/DevUtilHostnamePortTest.java

Added logic to parse message in json format
Fixes https://github.com/OpenLiberty/ci.maven/issues/1923
run mvn liberty:devc for sample project shared in issue
https://github.com/adityarao2005/open-liberty-docker-devc-break-example
port in message is parsed successfully and showing properly in warning message
PR's for testing in 
* ci.maven https://github.com/OpenLiberty/ci.maven/pull/1924
* ci.gradle https://github.com/OpenLiberty/ci.gradle/pull/992

 https port parsing logic fixed for json message format
