OpenLiberty/ci.common

pom.xml
src/main/java/net/wasdev/wlp/common/plugins/util/InstallFeatureUtil.java
src/test/java/net/wasdev/wlp/common/plugins/util/InstallFeatureUtilGetServerFeaturesTest.java
src/test/resources/servers/server_url.xml

For installing features, when parsing server.xml files, also handle features from included URLs.

Parse server.xml include URLs

---

src/main/java/net/wasdev/wlp/common/plugins/util/InstallFeatureUtil.java
src/test/java/net/wasdev/wlp/common/plugins/util/InstallFeatureUtilTest.java
src/test/resources/jsons/ol.json
src/test/resources/jsons/other.json
src/test/resources/jsons/wlp.json

For https://github.com/WASdev/ci.maven/issues/381

Automatically accept license if installing only Open or WebSphere Liberty features from Maven Central

---

src/main/java/net/wasdev/wlp/common/plugins/util/InstallFeatureUtil.java
src/test/java/net/wasdev/wlp/common/plugins/util/InstallFeatureUtilTest.java

Addresses https://github.com/WASdev/ci.maven/issues/415

When installing features, combine feature sets with case insensitive matching

---

src/main/java/net/wasdev/wlp/common/plugins/util/DevUtil.java
src/main/java/net/wasdev/wlp/common/plugins/util/InstallFeatureUtil.java
src/main/java/net/wasdev/wlp/common/plugins/util/ServerFeatureUtil.java

**Installing features added to the server.xml**
- matches logic in InstallFeatureUtil for getServerFeatures
**Creating missing directories when dev mode is running**
- java source & java test files: if either directories are created an initial compile is done by calling the maven-compiler-plugin and the app is installed by calling the liberty-maven-plugin.

added new util for getServerFeatures

---

src/main/java/net/wasdev/wlp/common/plugins/util/DevUtil.java

Add try/catch to avoid file not found exception when copying file.

Avoid file not found exception

---

src/main/java/net/wasdev/wlp/common/plugins/util/DevUtil.java

Change the default to run tests when pressing Enter.  Also allow a property to enable hot testing after changes are made.

Run tests on Enter

---

src/test/java/net/wasdev/wlp/common/plugins/util/DevUtilTest.java

Add a unit test for `enableServerDebug`.

Dev mode debug unit tests

---

src/main/java/net/wasdev/wlp/common/plugins/util/DevUtil.java
src/test/java/net/wasdev/wlp/common/plugins/util/BaseDevUtilTest.java
src/test/java/net/wasdev/wlp/common/plugins/util/DevUtilRunTestThreadTest.java
src/test/java/net/wasdev/wlp/common/plugins/util/DevUtilTest.java

Support exit command to exit dev mode in addition to ctrl-c

Support exit command

---

src/main/java/net/wasdev/wlp/common/plugins/util/DevUtil.java
src/test/java/net/wasdev/wlp/common/plugins/util/DevUtilTest.java

Fixes https://github.com/WASdev/ci.maven/issues/489

Find available debug port when starting dev mode

---

.travis.yml
src/main/java/net/wasdev/wlp/common/plugins/util/InstallFeatureUtil.java

Resolves an issue with the installation of some features, where the call to `productInfo validate` was hanging and timing out.

More reliabily read output from productInfo validate

---

src/main/java/net/wasdev/wlp/common/plugins/util/DevUtil.java

Fix merge from #62

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

- If the first java file is being created in the project, create the `classes` directory before compiling.
- If any new directory is being added, start watching the directory
Fixes https://github.com/OpenLiberty/ci.maven/issues/542

Track creating first java file or new directory

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Fix for https://github.com/OpenLiberty/ci.maven/issues/548

Fix deleting test sources

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

- If input is unavailable, avoid infinite loop (fix for https://github.com/OpenLiberty/ci.maven/issues/546)
- Re-print the "press enter" message after tests run, even if tests failed
- Print message depending on whether input is available.

Fix input detection and message prompt

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
src/test/java/io/openliberty/tools/common/plugins/util/DevUtilTest.java

Fixes https://github.com/OpenLiberty/ci.maven/issues/545

Overwrite server.env.bak if it already exists

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

For https://github.com/OpenLiberty/ci.maven/issues/582

Enable q or quit to exit dev mode

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Fixes https://github.com/OpenLiberty/ci.maven/issues/610

Ignore workarea and logs when copying config dir

---

src/main/java/io/openliberty/tools/common/plugins/util/ServerFeatureUtil.java

Fixes https://github.com/OpenLiberty/ci.maven/issues/607

Close input stream for bootstrap props

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

fixes https://github.com/OpenLiberty/ci.maven/issues/586

increased verifyTimeout and improved timeout messages

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Fixes https://github.com/OpenLiberty/ci.maven/issues/603

Ignore file name patterns during changes

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

This is in support of ci.maven issue https://github.com/OpenLiberty/ci.maven/issues/534. This PR and ci.maven PR https://github.com/OpenLiberty/ci.maven/pull/625.

update exceptions thrown and caught

---

src/main/java/io/openliberty/tools/common/plugins/config/ServerConfigDocument.java

Resolves issue https://github.com/OpenLiberty/ci.maven/issues/633.

Add file exists check for absolute file

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
src/test/java/io/openliberty/tools/common/plugins/util/BaseDevUtilTest.java

Part of https://github.com/OpenLiberty/ci.maven/issues/629

Move app startup verification to before ITs

---

src/main/java/io/openliberty/tools/common/plugins/config/ServerConfigDropinXmlDocument.java

This is needed by ci.maven PR https://github.com/OpenLiberty/ci.maven/pull/635.

Add file to generate server config xml

---

src/main/java/io/openliberty/tools/common/plugins/util/InstallFeatureUtil.java

This is a fix for ci.maven issue https://github.com/OpenLiberty/ci.maven/issues/669. A test will be added for that issue in ci.maven.

fix productInfo path problem

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Fixes https://github.com/OpenLiberty/ci.maven/issues/674

Change timeout message to seconds

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Fixes https://github.com/OpenLiberty/ci.maven/issues/622

support for deleting java src directories or config directories

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Fixes https://github.com/OpenLiberty/ci.maven/issues/630
Track java source and test classes that could not compile and continually try to compile them when new classes are added/modified or the build file is updated.

recompile existing classes when classes added/changed or build file updated

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Fix for https://github.com/OpenLiberty/ci.maven/issues/627

initially compile java source and test classes

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Support reloading properties files on change, if properties files are specified by the calling plugin.  This is needed for https://github.com/OpenLiberty/ci.gradle/issues/367

Reload properties files on change

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Partial fix for https://github.com/OpenLiberty/ci.gradle/issues/387

warning message for invalid verifyAppStartTimeout or serverStartTimeout

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Fixes https://github.com/OpenLiberty/ci.maven/issues/687

Added instructions for quitting dev mode

---

src/main/java/io/openliberty/tools/common/plugins/config/ServerConfigDocument.java

This is for gradle issue https://github.com/OpenLiberty/ci.gradle/issues/426.

Fix variable resolution for variables starting with env.

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Fixes https://github.com/OpenLiberty/ci.maven/issues/639 and https://github.com/OpenLiberty/ci.maven/issues/728

Include update message in app start up verification search

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
src/test/java/io/openliberty/tools/common/plugins/util/BaseDevUtilTest.java

Add a polling option for scenarios where file system notifications are not available, e.g. on mounted directories in Docker on Windows.
Fix is for https://github.com/OpenLiberty/ci.maven/issues/617

Add polling option for dev mode

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

When starting the server, dev mode waits for updates to messages.log before checking its contents.  Change this to use polling instead of WatchService.  This is regardless of the `polling` parameter since it's just for one specific scenario, and it doesn't make sense to maintain two different implementations for this.

Use polling when checking for log update during startServer

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

https://github.com/OpenLiberty/ci.maven/issues/702

702 properties changes

---

src/main/java/io/openliberty/tools/common/arquillian/objects/LibertyManagedObject.java

For https://github.com/OpenLiberty/liberty-arquillian/pull/70

Add useDir property

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Part of https://github.com/openliberty/ci.maven/issues/741

Increase dev mode server start timeout

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
src/test/java/io/openliberty/tools/common/plugins/util/BaseDevUtilTest.java

Fixes https://github.com/OpenLiberty/ci.maven/issues/748

Auto detect file tracking method

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
src/test/java/io/openliberty/tools/common/plugins/util/BaseDevUtilTest.java

Part of https://github.com/OpenLiberty/ci.maven/issues/787

Enable dev mode container option

---

src/main/java/io/openliberty/tools/common/arquillian/util/HttpPortUtil.java
src/test/java/io/openliberty/tools/common/arquillian/util/HttpPortUtilTest.java

For ci.maven issue https://github.com/OpenLiberty/ci.maven/issues/713.

Look in generated config variable file for httpPort

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
src/test/java/io/openliberty/tools/common/plugins/util/BaseDevUtilTest.java

Use dockerRunOpts param from Maven and Gradle instead of system property.
Part of https://github.com/OpenLiberty/ci.maven/issues/795

Add dockerRunOpts

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Completes https://github.com/openliberty/ci.maven/issues/804

804 enable debug mode

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

For the issue https://github.com/OpenLiberty/ci.maven/issues/800

Stop and start the container when a file is changed.

---

pom.xml
src/main/java/io/openliberty/tools/common/arquillian/util/HttpPortUtil.java
src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
src/test/java/io/openliberty/tools/common/arquillian/util/HttpPortUtilTest.java

Merge from master to correspond with https://github.com/OpenLiberty/ci.maven/pull/855
(There were no merge conflicts here).

Merge from master

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Fixes https://github.com/OpenLiberty/ci.maven/issues/845

Mount files from COPY lines

---

src/main/java/io/openliberty/tools/common/plugins/config/LooseConfigData.java
src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Address comments from https://github.com/OpenLiberty/ci.common/pull/155

Address review comments

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
src/test/java/io/openliberty/tools/common/plugins/util/DevUtilPrepareDockerfileTest.java
src/test/resources/dockerbuild/basic-expected.txt
src/test/resources/dockerbuild/basic.txt
src/test/resources/dockerbuild/copyParsing-expected.txt
src/test/resources/dockerbuild/copyParsing.txt
src/test/resources/dockerbuild/multiline-expected.txt
src/test/resources/dockerbuild/multiline.txt
src/test/resources/dockerbuild/multilineEscape-expected.txt
src/test/resources/dockerbuild/multilineEscape.txt

Handle Dockerfile with COPY commands that span multiple lines and have comments in between
Fixes https://github.com/OpenLiberty/ci.maven/issues/863

Handle Dockerfiles with multiline and comments

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
src/test/java/io/openliberty/tools/common/plugins/util/DevUtilPrepareDockerfileTest.java

https://github.com/OpenLiberty/ci.maven/issues/878

Clear the list of files to mount before processing files starts.

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

https://github.com/OpenLiberty/ci.maven/issues/865

Set up permissions for the logs directory on Linux.

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Addresses https://github.com/OpenLiberty/ci.maven/issues/889 and https://github.com/OpenLiberty/ci.gradle/issues/505

Copy container error stream to devc output

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Testing shows the message is not displayed twice in the same line on Maven or Gradle.
Fixes https://github.com/OpenLiberty/ci.gradle/issues/506

Include docker build error message in exception to display in final build message

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Fixes https://github.com/OpenLiberty/ci.maven/issues/901

Show docker build command and better layout for the docker run command.

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Update variable name to match meaning of docker timeout parameter.

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Fixes https://github.com/OpenLiberty/ci.maven/issues/896

Print improved message when docker build times out.

---

pom.xml

Need to merge all three projects at one time.

Devc merged into master

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

This message is not likely to appear on Mac or Windows but can happen on Linux. The fix not to mount a missing file is also important on Linux.

One more issue in Devc to merge into master

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Fixes https://github.com/OpenLiberty/ci.maven/issues/903

Issue a warning if docker build takes longer than 30 secs.

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
src/test/java/io/openliberty/tools/common/plugins/util/BaseDevUtilTest.java

Part of https://github.com/OpenLiberty/ci.maven/issues/761

Redeploy after compile if not loose app

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Pass the build context into checkDockerIgnore() rather than regenerating the context inside that method. 
Fixes #189

Improve the code for maintainability

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Fixes https://github.com/OpenLiberty/ci.maven/issues/953

Trim Docker host port

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
src/test/java/io/openliberty/tools/common/plugins/util/DevUtilPrepareDockerfileTest.java
src/test/resources/dockerbuild/basic-expected.txt
src/test/resources/dockerbuild/multiline-expected.txt
src/test/resources/dockerbuild/multiline.txt

Fixes https://github.com/OpenLiberty/ci.maven/issues/965

Disable OpenJ9 SCC before configure.sh 

---

src/main/java/io/openliberty/tools/common/plugins/util/ServerFeatureUtil.java

Resolves https://github.com/OpenLiberty/ci.maven/issues/957

Add ability to resolve env vars for an include file from bootstrap

---

src/main/java/io/openliberty/tools/common/plugins/util/ServerFeatureUtil.java

More changes for https://github.com/OpenLiberty/ci.maven/issues/957

Fix property resolution for include location attributes

---

src/main/java/io/openliberty/tools/common/plugins/util/ServerFeatureUtil.java

Another fix for OpenLiberty/ci.maven#957

Another fix for variable resolution

---

src/main/java/io/openliberty/tools/common/plugins/util/ServerFeatureUtil.java

Related to OpenLiberty/ci.maven#957

Fix for Windows path

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Fixes https://github.com/OpenLiberty/ci.maven/issues/985

Changed port mapping errors to warnings

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Fixes https://github.com/OpenLiberty/ci.maven/issues/818

Track the dockerfile specified or default and when changed, rebuild container

---

src/main/java/io/openliberty/tools/common/plugins/util/ServerFeatureUtil.java

Pass in Liberty directory property files

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Fixes https://github.com/OpenLiberty/ci.maven/issues/988
Also supports "--name ABC"

Support dockerRunOpts specify container name with --name=ABC

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

According to YK's suggestion.
Fixes #216

Update port conflict warning message.

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Fixes https://github.com/OpenLiberty/ci.maven/issues/960

Check if the docker run command is still running before trying to stop it

---

pom.xml
src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Fixes https://github.com/OpenLiberty/ci.maven/issues/1008

Before starting the server in container mode, check the Docker Client version

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

`docker build --pull` on dev mode startup
`docker build` (no pull) if the image is being rebuilt during dev mode, to prevent the Liberty image from being possibly updated while dev mode is running.
Part of https://github.com/OpenLiberty/ci.maven/issues/1016

docker pull on devc startup

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Fixes https://github.com/OpenLiberty/ci.maven/issues/868

Show error on JVM version mismatch

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Fixes https://github.com/OpenLiberty/ci.maven/issues/964
**Design Description** 
We need to keep the first check for debug port in order to populate server.env. But then we execute docker build which depends on server.env and which can run for 5 minutes if you need to pull an image from docker.com (or other repository). Only then can we execute docker run which binds the ports selected earlier. This is a race condition if you start another dev mode during this window.
Thus we must add a second availability check for debug port just before docker run. If we detect a conflict, the server in the container can still use the port specified in server.env but the docker run will map it to an ephemeral local host port.

Check debug port a second time to avoid port conflict.

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Fixes https://github.com/OpenLiberty/ci.maven/issues/1028

Avoid port conflict warning if http/https port simply not set

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Fixes https://github.com/OpenLiberty/ci.maven/issues/1030

Untrack directories on Dockerfile change

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Fixes https://github.com/OpenLiberty/ci.maven/issues/1032

Check if port is mapped before showing non-default mapped port warning

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
src/test/java/io/openliberty/tools/common/plugins/util/DevUtilTest.java

Fixes https://github.com/OpenLiberty/ci.maven/issues/1034

Use different port conflict method for Windows

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Change the Docker version number to 18.03.0

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Fixes https://github.com/OpenLiberty/ci.maven/issues/934

Check for docker run exit value 143 caused by docker stop

---

src/main/java/io/openliberty/tools/common/plugins/util/AbstractContainerSupportUtil.java
src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
src/main/java/io/openliberty/tools/common/plugins/util/InstallFeatureUtil.java
src/main/java/io/openliberty/tools/common/plugins/util/ServerFeatureUtil.java
src/test/java/io/openliberty/tools/common/plugins/util/BaseDevUtilTest.java
src/test/java/io/openliberty/tools/common/plugins/util/BaseInstallFeatureUtilTest.java

Part of https://github.com/OpenLiberty/ci.maven/issues/811
- Increase docker build timeout to 600 seconds.
- If feature not found messages occur, give a warning suggesting to add RUN features.sh
- Install features using featureUtility and mounted Maven cache (but skip during dev mode startup and container rebuilds)

Install features to container

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Fixes https://github.com/OpenLiberty/ci.maven/issues/1059

Do not file-watch URLs used in Dockerfile

---

src/main/java/io/openliberty/tools/common/plugins/util/InstallFeatureUtil.java
src/test/java/io/openliberty/tools/common/plugins/util/BaseInstallFeatureUtilTest.java

Part of https://github.com/OpenLiberty/ci.maven/issues/811

Prevent error if features are already installed

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Fixes https://github.com/OpenLiberty/ci.maven/issues/1058

Check the image name for compliance with Docker rules.

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
src/test/java/io/openliberty/tools/common/plugins/util/BaseDevUtilTest.java

Part of https://github.com/OpenLiberty/ci.maven/issues/486

Use separate compile and test classpaths

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
src/test/java/io/openliberty/tools/common/plugins/util/BaseDevUtilTest.java
src/test/java/io/openliberty/tools/common/plugins/util/DevUtilPrepareDockerfileTest.java
src/test/resources/dockerbuild/dockerBuildContext.txt

- Support ear projects with devc.  
- Loose app is mounted to the top level multi module project directory if defined, or otherwise the current project directory.
- Support optional dockerBuildContext parameter

Support ear projects with devc

---

src/test/java/io/openliberty/tools/common/plugins/util/BaseDevUtilTest.java

Add required method to local class definition.

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Always run tests on startup for hotTests scenario

---

src/main/java/io/openliberty/tools/common/plugins/util/InstallFeatureUtil.java

Part of https://github.com/OpenLiberty/ci.maven/issues/1142

Remove stacktrace from override bundle debug message

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Fixes https://github.com/OpenLiberty/ci.maven/issues/1190

Include exception if tests failed to run during dev mode

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
src/main/java/io/openliberty/tools/common/plugins/util/ProjectModule.java
src/test/java/io/openliberty/tools/common/plugins/util/BaseDevUtilTest.java

Part of https://github.com/OpenLiberty/ci.maven/issues/1194

Skip source compile for ear/pom packaging

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

When `recompileDependencies=false` for a multi module project, try to compile failing classes from upstream projects and failing classes from downstream classes (in build order). 

Fix for recompileDeps=false multi module logic

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Use debug instead of warn as to not flood dev mode output

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Part of https://github.com/OpenLiberty/ci.maven/issues/1215
Will also add ITs in ci.maven

Wait timeout before recompiling due to build file change

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
src/main/java/io/openliberty/tools/common/plugins/util/ServerFeatureUtil.java

Also scan for Liberty features when you change server.xml or file1 in serverXmlFile=file1.
Update a comment for correctness.

When an upstream project builds Java then scan it for new Liberty features

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Fix for OpenLiberty/ci.maven#1223

Check for serverXmlFile option before processing other config files.

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
src/main/java/io/openliberty/tools/common/plugins/util/ProjectModule.java
src/test/java/io/openliberty/tools/common/plugins/util/BaseDevUtilTest.java

Part of https://github.com/OpenLiberty/ci.maven/issues/1226
See https://github.com/OpenLiberty/ci.maven/pull/1228 

Update artifact paths when a parent module dependency is added

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Part of https://github.com/OpenLiberty/ci.maven/pull/1228 

Initialize empty parent build file map if null

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
src/main/java/io/openliberty/tools/common/plugins/util/InstallFeatureUtil.java
src/test/java/io/openliberty/tools/common/plugins/util/BaseDevUtilTest.java

Partial fix for https://github.com/OpenLiberty/ci.maven/issues/1247
See https://github.com/OpenLiberty/ci.maven/pull/1253
- Added more detail to feature conflict error thrown from `InstallFeatureUtil`
- Follow up issues have been marked as `TODO`

Install features as part of generate features

---

src/main/java/io/openliberty/tools/common/plugins/util/ServerFeatureUtil.java
src/test/java/io/openliberty/tools/common/plugins/util/InstallFeatureUtilGetServerFeaturesTest.java

Enhance class to return the list of server features with original mixed case

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
src/main/java/io/openliberty/tools/common/plugins/util/InstallFeatureUtil.java
src/test/java/io/openliberty/tools/common/plugins/util/BaseDevUtilTest.java

Reverts OpenLiberty/ci.common#296

Revert "Install features as part of generate features"

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
src/main/java/io/openliberty/tools/common/plugins/util/ProjectModule.java
src/test/java/io/openliberty/tools/common/plugins/util/BaseDevUtilTest.java

- track source class files for feature generation
- on class file change, pass changed class files to the Liberty feature generation
See https://github.com/OpenLiberty/ci.maven/pull/1275
See https://github.com/OpenLiberty/ci.gradle/pull/640

Track class files for feature generation

---

src/main/java/io/openliberty/tools/common/plugins/util/InstallFeatureUtil.java

Fixes https://github.com/OpenLiberty/ci.maven/issues/1277

Remove method to read Liberty json from Maven repo.

---

src/main/java/io/openliberty/tools/common/plugins/config/LooseApplication.java
src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
src/test/java/io/openliberty/tools/common/plugins/util/BaseDevUtilTest.java
src/test/java/io/openliberty/tools/common/plugins/util/DevUtilRunTestThreadTest.java
src/test/java/io/openliberty/tools/common/plugins/util/DevUtilTest.java

Signed-off-by: Adam Wisniewski <awisniew@us.ibm.com>
Add web resource checking for ci.maven "exploded" loose war app support

Add webResource watching

---

src/main/java/io/openliberty/tools/common/plugins/util/BinaryScannerUtil.java

The only snag is the logging function. Used the technique from DevUtil.

Add methods to make the binary scanner accessible in a common project.

---

src/main/java/io/openliberty/tools/common/plugins/config/LooseApplication.java
src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
src/test/java/io/openliberty/tools/common/plugins/util/BaseDevUtilTest.java
src/test/java/io/openliberty/tools/common/plugins/util/DevUtilRunTestThreadTest.java
src/test/java/io/openliberty/tools/common/plugins/util/DevUtilTest.java

Reverts OpenLiberty/ci.common#309

Revert "Add webResource watching"

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

On Maven, dev mode calls generate features and then does an initial Java compile.  Skip generate features during this initial Java compile since it was already performed during the dev mode startup calls.
Note: It does not need to check the `initialCompile` flag since the code finds the compiled classes RIGHT AFTER the initial compile.
Fixes https://github.com/OpenLiberty/ci.maven/issues/1293

Skip generate features after dev mode startup on Maven

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
src/main/java/io/openliberty/tools/common/plugins/util/ServerFeatureUtil.java

See https://github.com/OpenLiberty/ci.maven/pull/1312

Utilize ServerFeatureUtil for generate features

---

src/main/java/io/openliberty/tools/common/plugins/config/LooseApplication.java
src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
src/test/java/io/openliberty/tools/common/plugins/util/BaseDevUtilTest.java
src/test/java/io/openliberty/tools/common/plugins/util/DevUtilRunTestThreadTest.java
src/test/java/io/openliberty/tools/common/plugins/util/DevUtilTest.java

Signed-off-by: Adam Wisniewski <awisniew@us.ibm.com>

Add web resource support

---

src/main/java/io/openliberty/tools/common/plugins/config/ServerConfigXmlDocument.java

See https://github.com/OpenLiberty/ci.maven/pull/1319 and https://github.com/OpenLiberty/ci.gradle/pull/664

Add createFeatureManager method to ServerConfigXmlDocument

---

src/main/java/io/openliberty/tools/common/plugins/util/ServerFeatureUtil.java

Remove leftover comment from  merge

---

src/main/java/io/openliberty/tools/common/plugins/util/BinaryScannerUtil.java

Thought this might be useful information for debugging in the future.

Debug statement to show parameters for binary scanner call

---

src/main/java/io/openliberty/tools/common/plugins/util/BinaryScannerUtil.java
src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
src/test/java/io/openliberty/tools/common/plugins/util/BaseDevUtilTest.java

Improve exception handling for feature generation

---

src/main/java/io/openliberty/tools/common/plugins/util/InstallFeatureUtil.java

Improve conflict logic in InstallFeatureUtil

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Part of https://github.com/OpenLiberty/ci.maven/issues/1291
See https://github.com/OpenLiberty/ci.maven/pull/1349

Create setFeatureGeneration method

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Fixes https://github.com/OpenLiberty/ci.maven/issues/1332

1332 install order

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Only run genFeatures if server.xml is modified

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Fixes https://github.com/OpenLiberty/ci.maven/issues/1357

Dev mode, only track class files if generateFeatures=true

---

src/main/java/io/openliberty/tools/common/plugins/util/BinaryScannerUtil.java

Fixes https://github.com/OpenLiberty/ci.maven/issues/1365

Remove unused exception.

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Do not run generate features if there are classes failing to compile

---

src/main/java/io/openliberty/tools/common/plugins/util/BinaryScannerUtil.java

Add defined constants to manage proper input to binary scanner.

---

src/main/java/io/openliberty/tools/common/plugins/config/ServerConfigXmlDocument.java
src/test/java/io/openliberty/tools/common/plugins/util/ServerConfigFileTest.java

or as the first line after <server> if there is no <featureManager>.
This requires some test case changes.
Fixes https://github.com/OpenLiberty/ci.maven/issues/1410

Insert the server.xml comment just before the <featureManager> element

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Fixes https://github.com/OpenLiberty/ci.maven/issues/1440 
Fixes https://github.com/OpenLiberty/ci.maven/issues/1437
Fixes https://github.com/OpenLiberty/ci.gradle/issues/716

Do not generate features on server restart

---

src/main/java/io/openliberty/tools/common/plugins/util/BinaryScannerUtil.java

Once this is merged we'll need to install the jar to the local maven repository until the jar is uploaded to sonatype.

Call the binary scanner using the new API: new names, log location and log level

---

src/main/java/io/openliberty/tools/common/plugins/util/BinaryScannerUtil.java

Version numbers obtained from the binary scanner. 

Add the MicroProfile sub-versions supported by the binary scanner

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Partial fix for https://github.com/OpenLiberty/ci.maven/issues/1458
See https://github.com/OpenLiberty/ci.maven/pull/1478 and https://github.com/OpenLiberty/ci.gradle/pull/731

Copy generated features file to temp server directory before calling install features

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Fixes https://github.com/OpenLiberty/ci.maven/issues/1369
Reduces output in the dev mode console when a source file change occurs but the generated-features.xml file remains the same.
Source file change but no new API usage, ci.maven output:
```
[INFO] Source compilation was successful.
[INFO] Running liberty:generate-features
[INFO] [AUDIT   ] CWWKZ0009I: The application demo-devmode-maven has stopped successfully.
[INFO] [AUDIT   ] CWWKZ0003I: The application demo-devmode-maven updated in 0.258 seconds.
[INFO] Generated the following features: [mpHealth-3.1, jaxrs-2.1]
```
Source file change but no new API usage, ci.gradle output:
```
> Task :compileJava UP-TO-DATE
> Task :processResources NO-SOURCE
BUILD SUCCESSFUL in 108ms
1 actionable task: 1 up-to-date
> Task :libertyDev
Source …
```

Do not copy generated features file to server dir if features have not changed

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
src/main/java/io/openliberty/tools/common/plugins/util/InstallFeatureUtil.java
src/test/java/io/openliberty/tools/common/plugins/util/BaseDevUtilTest.java

Part of https://github.com/OpenLiberty/ci.maven/issues/1471
See https://github.com/OpenLiberty/ci.maven/pull/1482 and https://github.com/OpenLiberty/ci.gradle/pull/733

Pass generateFeatures value to installFeatures

---

src/main/java/io/openliberty/tools/common/plugins/util/BinaryScannerUtil.java

Part of https://github.com/OpenLiberty/ci.maven/issues/1474 
Will hold off on merging until new binary scanner jar is in Sonatype

Handle FeatureNotAvailableAtRequestedLevelException from binary app scanner

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Disable feature generation hotkeys

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Fixes https://github.com/OpenLiberty/ci.maven/issues/1469

1469 update class file tracking

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Only count log messages when compiling and needing to test.

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Fixes https://github.com/OpenLiberty/ci.maven/issues/1511

Track classes that we failed to generate features for

---

src/main/java/io/openliberty/tools/common/plugins/util/BinaryScannerUtil.java

Part of https://github.com/OpenLiberty/ci.maven/issues/1515
See https://github.com/OpenLiberty/ci.maven/pull/1516

Add string to represent EE or MP version higher than stored versions

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Fixes https://github.com/OpenLiberty/ci.maven/issues/1526. See https://github.com/OpenLiberty/ci.maven/pull/1531
We no longer need this check on config file change:
```java
if (isGeneratedFeaturesFile && !generatedFeaturesModified) {
// features in the generated features file did not change, do not copy this file
// to the server directory
debug("The features in " + generatedFeaturesFile + " have not been modified.");
}
```
as the generated-features.xml file will not be modified unless new features were generated.
Also remove unnecessary copyFile duplicate code. 

Remove unnecessary checks for config file change logic

---

src/main/java/io/openliberty/tools/common/plugins/util/ProjectModule.java

Signed-off-by: Scott Kurz <skurz@us.ibm.com>
Feel free to tack this onto something else if it's more convenient.

Add toString for ProjectModule

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Signed-off-by: Scott Kurz <skurz@us.ibm.com>
Fixes https://github.com/OpenLiberty/ci.maven/issues/1575

Disable docker scan suggestion on devc docker build

---

src/main/java/io/openliberty/tools/common/plugins/util/JavaCompilerOptions.java
src/test/java/io/openliberty/tools/common/plugins/util/JavaCompilerOptionsTest.java

New pull request for issue #743 from my work account. CLA paperwork will follow soon.

issue #743 use project encoding for compilation

---

src/main/java/io/openliberty/tools/common/plugins/config/ServerConfigDocument.java
src/main/java/io/openliberty/tools/common/plugins/util/PropertyUtil.java
src/main/java/io/openliberty/tools/common/plugins/util/ServerFeatureUtil.java

These changes are needed for https://github.com/OpenLiberty/ci.maven/issues/1145.

Resolve variables for application location

---

src/main/java/io/openliberty/tools/common/plugins/util/PrepareFeatureUtil.java

The key for getting exception should be to `action.exception.stacktrace`

fix debug trace for prepareFeature goal

---

src/main/java/io/openliberty/tools/common/plugins/util/InstallFeatureUtil.java
src/test/java/io/openliberty/tools/common/plugins/util/InstallFeatureUtilTest.java

For https://github.com/OpenLiberty/ci.maven/issues/1682

Issue warning for empty feature and remove from collection

---

src/main/java/io/openliberty/tools/common/plugins/util/ServerFeatureUtil.java

One more place to check for empty feature, issue warning and skip adding to the collection.

Check for empty feature

---

pom.xml
src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
src/main/java/io/openliberty/tools/common/plugins/util/InstallFeatureUtil.java
src/main/java/io/openliberty/tools/common/plugins/util/PrepareFeatureUtil.java
src/main/java/io/openliberty/tools/common/plugins/util/VersionUtility.java

Remove maven-artifact dependency

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
src/test/java/io/openliberty/tools/common/plugins/util/BaseDevUtilTest.java

For Maven issue https://github.com/OpenLiberty/ci.maven/issues/1646.
Used by Gradle PR [825](https://github.com/OpenLiberty/ci.gradle/pull/825) and Maven PR [1672](https://github.com/OpenLiberty/ci.maven/pull/1672).

Add new skip install feature flag for dev mode

---

src/main/java/io/openliberty/tools/common/plugins/util/PrepareFeatureUtil.java

Fix NPE from issue https://github.com/OpenLiberty/ci.maven/issues/1615. This does not fix the root problem, as that is still unknown.

Fix NPE on stream close

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java

Fixes missing directory and permissions issues on Windows

Create devc temp dirs on Windows

---

src/main/java/io/openliberty/tools/common/arquillian/util/HttpPortUtil.java
src/main/java/io/openliberty/tools/common/plugins/config/ServerConfigDocument.java
src/main/java/io/openliberty/tools/common/plugins/config/XmlDocument.java
src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
src/main/java/io/openliberty/tools/common/plugins/util/PrepareFeatureUtil.java
src/main/java/io/openliberty/tools/common/plugins/util/ServerFeatureUtil.java

Fix xml file processing

---

src/main/java/io/openliberty/tools/common/plugins/config/ServerConfigDocument.java

init libertyDirectoryPropertyToFile

---

src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
src/test/java/io/openliberty/tools/common/plugins/util/BaseDevUtilTest.java

For https://github.com/OpenLiberty/ci.gradle/issues/890

changes for key binding for on demand tests in dev mode

---

pom.xml
src/main/java/io/openliberty/tools/common/plugins/util/InstallFeatureUtil.java

Check runtime version for versionless features

---

src/main/java/io/openliberty/tools/common/plugins/util/InstallFeatureUtil.java

Update min version for versionless feature support to 24.0.0.10

---

src/main/java/io/openliberty/tools/common/plugins/config/ServerConfigDocument.java
src/main/java/io/openliberty/tools/common/plugins/util/ServerFeatureUtil.java
src/main/java/io/openliberty/tools/common/plugins/util/VariableUtility.java
src/test/java/io/openliberty/tools/common/plugins/util/InstallFeatureUtilGetServerFeaturesTest.java
src/test/resources/servers/server.env
src/test/resources/servers/server_include_variable.xml
src/test/resources/servers/server_include_variable_default_value.xml

Fixes [#1860](https://github.com/OpenLiberty/ci.maven/issues/1860)

 variable resolution added for include in install feature

---

src/main/java/io/openliberty/tools/common/plugins/config/ServerConfigDocument.java
src/main/java/io/openliberty/tools/common/plugins/util/LibertyPropFilesUtility.java
src/main/java/io/openliberty/tools/common/plugins/util/ServerFeatureUtil.java
src/test/java/io/openliberty/tools/common/config/ServerConfigDocumentOverridesTest.java
src/test/java/io/openliberty/tools/common/plugins/util/LibertyPropFilesUtilityTest.java

Changes made to support all predefined variables 
Integrated with LCLS, LGP and LMP
https://github.com/OpenLiberty/liberty-language-server/pull/346
https://github.com/OpenLiberty/ci.gradle/pull/932
https://github.com/OpenLiberty/ci.maven/pull/1864

 changes to support pre defined variables
